# Generated by Django 4.2.13 on 2024-08-07 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MotorInsuranceCompany', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='policy',
            name='breakdown_assistance',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='policy',
            name='passenger_cover',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='policy',
            name='personal_accident',
            field=models.BooleanField(default=False),
        ),
    ]
